### ISSUE TITLE
I tried Anbox on the Nexus 5 

### ISSUE THREAD

**Issue by Zig-03** [ubports/docs.ubports.com#147]
I saw that there is a hammerhead img http://cdimage.ubports.com/anbox-images/ and I decided to try it out. 
While following this tutorial http://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html?highlight=anbox I decided to use _boot_ as my PARTITIONNAME (IDK which one is actually the right one) and _hammerhead_ as my CODENAME. The end result is a device that is stuck at boot after I ran the `sudo fastboot reboot` command :) _I'll have to reflash Ubuntu Touch on it again._ What have I done wrong? Any help please? 

Also why not provide the boot name for the rest of the devices since you already provide an image for them? Thanks. 

**edit:** Apparently only this command didn't work `sudo fastboot reboot` and I just had to turn the phone off and back on. All the other steps were successful and Anbox worked nicely as well. Overall I'm satisfied with the results.

**Comment by UniversalSuperBox** [comment]
Support for Anbox is handled in [our forum](https://forums.ubports.com), but you do highlight a good point. Either we need to update the Anbox documentation to account for recent changes or remove it altogether.

Since Anbox is in "Daily Use", I think we should remove it. It's not ready for daily use at all.

@NeoTheThird, what do you think?

**Comment by Zig-03** [comment]
Hi @UniversalSuperBox I've edited my first post ;)
