### ISSUE TITLE
Add landing pages

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/docs.ubports.com#3]
Start from a good foundation and build from there, I always say.

Before we start writing a bunch of documents, we should get our landing pages in place. These include our indexes for top-level categories and each subcategory under them.

-   [ ]  About (About UBports, documentation structure)
-   [x]  User Guide
-   [x]    Installation
-   [x]   Daily Use
-   [x]   Hacking (Fancy command line stuff, things that require writable root)
-   [x]  Contribution
-   [x]   Bug Reporting
-   [x]   App Development
-   [ ]   OS Development
-   [x]   Translation
-   [x]   Documentation
-   [x]   Monetary Support

See how these all fit together (since I can't nest them on GitHub) [here](https://forums.ubports.com/topic/467/i-need-help-reorganizing-the-wiki).

**Comment by doniks** [comment]
Just to be clear. Some of these pages will be *landing pages* like Daily Use that introduce the topic and then link to a bunch of other pages where the actual content is. 

Some other pages will not only be landing pages but will just hold the entirety of content on that topic: About, Monetary Support. But possible even Installation, Bug reporting, Translation and Documentation. 

Agree?

**Comment by UniversalSuperBox** [comment]
Yes, that is correct.

**Comment by doniks** [comment]
I just checked and it seems 
* Contribution is there
* Bug reporting is there 
* App development is there 
* Translation is there

**Comment by doniks** [comment]
@UniversalSuperBox 
* **Translation:** This is done ain't it? What do you miss?
* **About**: Shouldn't we simply move https://docs.ubports.com/en/latest/about/introduction.html one level up? I can't think of anything else to say.
* **OS Development:** Do you think it's good enough to introduce and link to Halium? Or should we actually put something like this https://wiki.ubports.com/wiki/UBports-Development-Information in place as well?

**Comment by NeoTheThird** [comment]
> About: Shouldn't we simply move https://docs.ubports.com/en/latest/about/introduction.html one level up? I can't think of anything else to say.

I think this is a good idea, or did you have something else in mind for that, @UniversalSuperBox? Maybe we could also put our process definitions in about, instead of contribute, with subsections for the HAL-, Middleware-, UI-, Marketing-, Community-, Infrastructure- and QA-steering committees, as well as Board of Trustees, Board of Directors and Membership Committee.

What i am also missing at the moment is a place for talking about the inner workings of the operating system and documenting APIs. Not automatically generated documentation like api-docs.ubports.com, but thorough descriptions of components that you write manually. I'd propose adding a new *Platform* category.

**Comment by Flohack74** [comment]
This is more or less done, isn´t it?

**Comment by UniversalSuperBox** [comment]
Yep
