### ISSUE TITLE
systemdev kernel and harware abstraction outdated

### ISSUE THREAD

**Issue by lduboeuf** [ubports/docs.ubports.com#580]
https://docs.ubports.com/en/latest/systemdev/kernel-hal.html

**Comment by doniks** [comment]
Can you elaborate in which way it is outdated?

**Comment by lduboeuf** [comment]
> Can you elaborate in which way it is outdated?

Well i'm not a specialist in that field. But when i see Ubports 5.1 Nexus 4 ...

**Comment by doniks** [comment]
I still don't get it. 

Are you saying Nexus 4 has received a new port based on a newer Halium? I guess this is not impossible, I've just never seen it. Just because something is old doesn't equate to it being "out" of date. The same old story of old Android kernels and binary drivers again...

Or has the device been formally dropped? Could also be. I'm not really too up to date on this.

**Comment by lduboeuf** [comment]
Oh you are right, maybe i was too asleep yesterday :) . I should have confused with another page that i don't remember of. I close this ticket, sorry
